### PR TITLE
Adding element kind

### PR DESCRIPTION
**Pull request by ThePlenkov**
Kind element - is a valid type

### CODE REVIEW

**Comment by daogrady** [comment]
Hi Petr, 

thanks for the contribution!
@johannes-vogel @David-Kunz could one of you please confirm that this is valid? Thanks!

Best,
Daniel

**Comment by ThePlenkov** [comment]
it would be great to proceed with this PR too. @daogrady  Thanks!

**Comment by daogrady** [comment]
Sure, can you please cite a relevant section from CAPire or show a runtime example so I can confirm this is valid?

**Comment by ThePlenkov** [comment]
well, I see your point. Indeed - doesn't seem like documented because it's not used in the compiled file, but if we talk about parsed model - the kind element is there. I don't already remember what was the purpose - but I had to filter out elements based on this kind in my code:
```
  const model = await cds.load('hana2cds');
  const db = await cds.connect.to('db', {
    model: model as never,
    kind: 'hana',
    credentials: requires?.db?.credentials,
  });

  for (const [entity, definiton] of Object.entries(db.entities)) {

    //define CSV headers
    const headers = Object.values(definiton.elements)
      .filter(
        (e) => (e.kind as kinds) === 'element' && e.type !== 'cds.Association'
      )
      .map((e) => e.name);
```

so it's a good point which other selector do we need to use.. I already do not remember why e.type !== 'cds.Association' was not enough to distiguish columns from assitiations.. may be need to check again. But this is a fact - that parsed model has kind: element  for all the elements. It's just a question - what is the case when elements have something else.. Probably i just don't need to use it all - will check it

**Comment by daogrady** [comment]
Hi @ThePlenkov ,

were you able to find something pointing to the existence of such a property? If not, I'd like to close this PR for now.

Best,
Daniel

**Comment by daogrady** [comment]
When you say "in the code", do you mean "in samples" (like in the bookstore), or "the cds implementation code"? In case of the former, please link any such example so I can confirm it is valid.

**Comment by ThePlenkov** [comment]
No no I mean CDs core code itself. They use it in conditional logic

**Comment by daogrady** [comment]
The general policy for things that are not documented in CAPire is, that they are not part of the API and are thus probably not documented on purpose. That goes especially for things that can only be found in the `@sap/cds` package implementation, as well as things you may find when inspecting runtime artefacts in the debugger.

@David-Kunz could you maybe chime in and clear up whether `'element'` (not: `'elements'`) is a valid `.kind`?

**Review by daogrady — APPROVED** [review]
I checked in with a team of the runtime and they confirmed that this change is indeed valid. Thanks for the contribution!

**Pull request merged**
